VM_NAME="gtm-max"
OS_TYPE="ubuntu"
CODENAME="noble"
IMG_URL="https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
HOSTNAME="gtm-max"
USERNAME="root"
PASSWORD="12345"
DISK_SIZE="50G"
MEMORY="32000"
CPUS="8"
SSH_PORT="2222"
GUI_MODE="false"
PORT_FORWARDS=""
IMG_FILE="/home/user/vms/gtm-max.img"
SEED_FILE="/home/user/vms/gtm-max-seed.iso"
CREATED="Mon Apr 27 07:15:39 PM UTC 2026"
